// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7ifwlYC0h3hndSARpyMuc-f62FukjQIc',
    appId: '1:884674213247:web:5b79267c1ba96a005dd64a',
    messagingSenderId: '884674213247',
    projectId: 'my-firebase-b9699',
    authDomain: 'my-firebase-b9699.firebaseapp.com',
    storageBucket: 'my-firebase-b9699.firebasestorage.app',
    measurementId: 'G-3FES3ET4DK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA9u5J3jxEd96SrNRPdDusgO2fjDGBOxQ',
    appId: '1:884674213247:android:70cd3bb19dc5a2155dd64a',
    messagingSenderId: '884674213247',
    projectId: 'my-firebase-b9699',
    storageBucket: 'my-firebase-b9699.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCCa7vZ5PXbb7S4WPf2XsknyWkdZyBj54',
    appId: '1:884674213247:ios:ffaf826306a84a7f5dd64a',
    messagingSenderId: '884674213247',
    projectId: 'my-firebase-b9699',
    storageBucket: 'my-firebase-b9699.firebasestorage.app',
    iosBundleId: 'com.example.deshiMart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCCa7vZ5PXbb7S4WPf2XsknyWkdZyBj54',
    appId: '1:884674213247:ios:ffaf826306a84a7f5dd64a',
    messagingSenderId: '884674213247',
    projectId: 'my-firebase-b9699',
    storageBucket: 'my-firebase-b9699.firebasestorage.app',
    iosBundleId: 'com.example.deshiMart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7ifwlYC0h3hndSARpyMuc-f62FukjQIc',
    appId: '1:884674213247:web:91a4e01e6b964d625dd64a',
    messagingSenderId: '884674213247',
    projectId: 'my-firebase-b9699',
    authDomain: 'my-firebase-b9699.firebaseapp.com',
    storageBucket: 'my-firebase-b9699.firebasestorage.app',
    measurementId: 'G-2JCMRC5Y1T',
  );
}
